kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: chai-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sachinchaudhary-system-engineer/argocd-project.git
    targetRevision: main
    path: projects/chai-app
  destination:
    server: https://192.168.179.128:6443 
    namespace: chai-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true