kind: Deployment
apiVersion: apps/v1
metadata:
  name: apache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache

  template:
    metadata:
      labels:
        app: apache
    
    spec:
      containers:
      - name: apache-container
        image: httpd:latest
        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"

---

kind: Service
apiVersion: v1
metadata:
  name: apache-service

spec:
  selector:
    app: apache
  
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP