apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-shop
  namespace: online-shop
spec:
  replicas: 4
  selector:
    matchLabels:
      app: online-shop
  template:
    metadata:
      labels:
        app: online-shop
    spec:
      containers:
      - name: online-shop
        image: amitabhdevops/online_shop:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"

---

Kind: Service
apiVersion: v1
metadata:
  name: online-shop-service
  namespace: online-shop

spec:
  selectors:
    apps: online-shop
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
