server:
  metrics:
    enabled: true
    service:
      enabled: true

repoServer:
  metrics:
    enabled: true
    service:
      enabled: true

applicationSet:
  metrics:
    enabled: true
    service:
      enabled: true

notifications:
  metrics:
    enabled: true
    service:
      enabled: true