kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: nginx-app
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/sachinchaudhary-system-engineer/argocd-project.git
    targetRevision: main
    path: projects/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true