kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: online-app
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/sachinchaudhary-system-engineer/argocd-project.git
    targetRevision: main
    path: projects/online-shop
  destination:
    server: https://192.168.179.128:6443
    namespace: online-shop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true