kind: ApplicationSet
apiVersion: argoproj.io/v1alpha1
metadata:
  name: generator
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - name: nginx
            path: projects/nginx
            namespace: nginx
          - name: online-shop
            path: projects/online-shop
            namespace: online-shop

  template:
    metadata:
      name: '{{ name }}-list'

    spec:
      project: default
      source:
        repoURL: https://github.com/sachinchaudhary-system-engineer/argocd-project.git
        targetRevision: main
        path: '{{ path }}'
      destination: 
        server: https://192.168.179.128:6443
        namespace: '{{ namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true